# ------------------------------------------------------------------------------
#  Copyright Christopher Kormanyos 2020 - 2024.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# ------------------------------------------------------------------------------

name: wide_integer
on:
  push:
    branches:
      - '**'
  pull_request:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
jobs:
  msvc-release-x64-vs2022:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: clone-boost-develop
        working-directory: ${{ runner.workspace }}
        run: |
          git clone -b develop --depth 1 https://github.com/boostorg/boost.git ${{ runner.workspace }}/boost-root
      - name: clone-boost-submods
        working-directory: ${{ runner.workspace }}/boost-root
        run: |
          git submodule update --init tools
          git submodule update --init libs/config
          git submodule update --init libs/multiprecision
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022
      - name: bootstrap-boost
        working-directory: ${{ runner.workspace }}/boost-root
        run: |
          ./bootstrap.bat vc143
          ./b2 headers toolset=msvc-14.3
      - name: msvc-release-x64-vs2022
        shell: cmd
        working-directory: ./
        run: |
          set INCLUDE=%cd%
          set INCLUDE=${{ runner.workspace }}\boost-root;%INCLUDE%
          MSBuild -m wide_integer_vs2022.sln -p:useenv=true -p:Configuration=Release -p:Platform=x64 /t:Rebuild
          dir %cd%\x64\Release\wide_integer_vs2022.exe
          %cd%\x64\Release\wide_integer_vs2022.exe
